rapidsai/dependency-file-generator

README.md, src/rapids_dependency_file_generator/cli.py, src/rapids_dependency_file_generator/constants.py, src/rapids_dependency_file_generator/rapids_dependency_file_generator.py, tests/test_cli.py, tests/test_rapids_dependency_file_generator.py
This PR adjusts the `rapids-dependency-file-generator` tool to be able to accommodate any arbitrary set of matrix values instead of just `cuda` and `arch` values.
=> Make `matrix` values generic

src/rapids_dependency_file_generator/rapids_dependency_file_generator.py
This PR includes some changes to ensure that the generated dependency files are written relative to the `dependencies.yaml` file.
=> Fix dependency file paths

.gitignore, src/rapids_dependency_file_generator/cli.py, src/rapids_dependency_file_generator/rapids_dependency_file_generator.py, tests/test_cli.py, tests/test_examples.py
This PR refactors some things to ensure that the `dependencies.yaml` file is only ever read from the file system a single time.
=> Refactor `dependencies.yaml` reading

src/rapids_dependency_file_generator/constants.py
Needed for cuda-python updates / 22.10.01 hotfix. We must prioritize `conda-forge` over `nvidia` to get the right `cuda-python` builds.
=> Swap conda-forge and nvidia channel priority.

.github/actions/build-test/action.yml, .github/workflows/build-test.yaml, .github/workflows/prs.yaml, .github/workflows/release.yaml, .github/workflows/semantic-pr-title.yaml, .releaserc.yaml, ci/pypi-publish.sh, ci/update-version.sh
This PR re-adds PyPI uploads to our new semantic-release process.
To make this work, the `build-test.yaml` file needed to be switched from a reusable job to a composite action so that the built files exist on the machine that will do the release.
=> fix: Add PyPI Uploads to semantic-release process

.github/workflows/pr.yaml, .github/workflows/semantic-pr-title.yaml, .releaserc.yaml, ci/build-test.sh, ci/pypi-publish.sh, ci/update-version.sh
As per the docs for [semantic-release/exec](https://github.com/semantic-release/exec), the `stdout` output for `publishCmd` can be used to add PyPI release information to `semantic-release`. This should make the PyPI release URL appear in the GitHub release body and the PR comments left by `semantic-release`.
=> fix: Update PyPI release information for `semantic-release`

.github/workflows/release.yaml, .gitignore, .releaserc.yaml, ci/update-versions.sh, package-lock.json, package.json, renovate.json
This PR configures [semantic-release/git](https://github.com/semantic-release/git) to commit release assets back to the repository.
This means that anytime a release is triggered, `semantic-release` will commit the files whose version numbers were updated in `ci/update-versions.sh` back to the repository.
Since this plugin introduces a third `npm` package (`@semantic-release/git`), I opted to create a proper `packages.json` file to record these dependencies and their versions (as opposed to installing the dependencies manually in the `release.yaml` workflow). With the addition of this `package.json` file, I've also added a config file for [renovate](https://github.com/renovatebot/renovate) which will help keep these dependencies up-to-date. We use `renovate` on other repositories like …
=> feat: Add support for release assets

src/rapids_dependency_file_generator/rapids_dependency_file_generator.py
There is currently a conditional statement that is incorrectly attempting to index a string instead of retrieving a value from a dictionary.
Instead of accessing `f["output"]`, it needs to be adjusted to `files[f]["output"]`
The code excerpt below shows a minimal reproducer of the problem and the solution.
```python
files = {'checks': {'matrix': {'cuda': ['11.8'], 'arch': ['x86_64'], 'py': ['3.10']}, 'output': 'conda', 'includes': ['checks', 'py_version']}}
for f in files:
f["output"]
for f in files:
files[f]["output"]
```
=> fix: Fix conditional statement

.github/workflows/release.yaml
Configures the release workflow to trigger `build-and-publish-images` workflow of `ci-imgs` due to being an upstream dependency.
=> feat: Trigger CI img rebuilds

.github/workflows/release.yaml
PR adds an identifier to the triggered downstream `ci-imgs` build so its easy to know which job triggered its run.
=> feat: Add upstream info

CONTRIBUTING.md
We recently merged two PRs that triggered unnecessary releases.
This PR updates the `CONTRIBUTING.md` file to specify what PR titles can be used to avoid triggering unnecessary releases.
=> docs: Update `CONTRIBUTING.md`

src/rapids_dependency_file_generator/rapids_dependency_file_validator.py
Closes #53 by replacing use of `pkg_resources` with `importlib.resources`. This should fix Python 3.12 support.
=> fix: Remove dependency on pkg_resources

src/rapids_dependency_file_generator/rapids_dependency_file_generator.py
This fix prevents a crash when using `--clean` on a repo where a file contains non-unicode characters. Fix seems benign since any file with non-unicode characters likely wasnt created by this tool.
Closes #58
=> fix: Avoid crash when file in repo contains non-unicode characters

.github/workflows/release.yaml
This PR replaces my personal access token with the `GITHUB_TOKEN` provided by GitHub Actions.
=> ci: Update `GITHUB_TOKEN` for `semantic-release`

.github/workflows/release.yaml, .releaserc.yaml, ci/semantic-release-success.sh
The `release.yaml` workflow currently triggers the `ci-imgs` repository to rebuild anytime a merge to `main` happens.
This PR makes the logic smarter by only triggering the `ci-imgs` repository to rebuild when an actual release occurs.
This will prevent `ci-imgs` rebuilds from occurring unnecessarily.
=> ci: Ensure `ci-imgs` repo is only triggered when new releases occur

src/rapids_dependency_file_generator/rapids_dependency_file_generator.py, tests/test_rapids_dependency_file_generator.py
Similar to #64, this proposes small changes to make bugs related to passing configuration between the project's functions less likely.
* requires that `make_dependency_file()` (which takes 7 arguments) only be called with keyword arguments
* removes default on `extras` in that function
`make_dependency_file()` is only called in one place, and that place supplies a value for `extras`.
https://github.com/rapidsai/dependency-file-generator/blob/36a40613235089b4de271367ccef3674678c1555/src/rapids_dependency_file_generator/rapids_dependency_file_generator.py#L442-L450
=> refactor: make configuration-passing from make_dependency_files() to make_dependency_file() stricter

.github/actions/semantic-release/action.yaml, .github/workflows/release.yaml, .releaserc.yaml, ci/publish/conda.sh
This PR updates the release scripts to ensure that DFG is uploaded to both the `rapidsai` and `rapidsai-nightly` Anaconda.org organizations.
=> fix: Upload conda package to both `rapidsai` & `rapidsai-nightly` orgs

src/rapids_dependency_file_generator/_cli.py, src/rapids_dependency_file_generator/_rapids_dependency_file_generator.py
Contributes to https://github.com/rapidsai/build-planning/issues/31.
Follow-up to https://github.com/rapidsai/rapids-build-backend/pull/17#discussion_r1576662655.
Proposes restricting `make_dependency_files()` to only accepting keyword arguments, to reduce the risk of oops-passed-this-in-the-wrong-order types of bugs, and to make code using it a little bit easier to read.
The only direct usage of that function outside of this project itself is in `rapids-build-backend`, and that's already using keyword arguments in its one call ([GitHub search](https://github.com/search?q=org%3Arapidsai%20%22make_dependency_files%22&type=code) | [rapids-build-backend code link](https://github.com/rapidsai/rapids-build-backend/blob/97a19504201f18cfae1864c8be99c1d73cbcc0f9/rapids_build_backend/impls.py#L198) …
=> chore(refactor): require keyword-only args in make_dependency_files()

MANIFEST.in
Contributes to #76 and #87.
Proposes adding a `py.typed` file, to advertise to type-checkers that this project contains inline type hints (i.e. doesn't ship a separate package of type stubs).
This is described in PEP 561: https://peps.python.org/pep-0561/
> *Package maintainers who wish to support type checking of their code MUST add a marker file named py.typed to their package supporting typing.*
This didn't really matter when `rapids-dependency-file-generator` was only being used as a CLI, but now that `rapids-build-backend` is consuming it as a library, I think this is useful to have. It means that `mypy`, `pyright`, etc. used to check `rapids-build-backend` will also consider `rapids_dependency_file_generator`'s type hints.
Built a wheel and confirmed that this file made it in with …
=> chore(refactor): add a py.typed file

src/rapids_dependency_file_generator/_rapids_dependency_file_generator.py, tests/test_rapids_dependency_file_generator.py
Contributes to #87.
`rapids-dependency-file-generator` handles deduplicating the sets of dependencies provided to it, including `pip: ` lists for conda environments.
This PR modifies the logic the function does that in the following ways:
* fixes return type hint
* refactors it so that:
- only a single pass is done over the inputs to split requirements in to pip vs non-pip
- assignments are done in a way that's a bit easier for a type checker to understand
This fixes these errors found by `mypy`:
```text
src/rapids_dependency_file_generator/_rapids_dependency_file_generator.py:65: error: Argument 1 to "append" of "list" has incompatible type "dict[str, list[str]]"; expected "str"  [arg-type]
src/rapids_dependency_file_generator/_rapids_dependency_file_generator.py:66: error: Incompatible …
```
=> fix: fix return type hint for dedupe()

src/rapids_dependency_file_generator/_config.py
Contributes to #87.
Proposes changing type hints using `object` to `typing.Any`.
This fixes 10 errors from `mypy`.
<details><summary>full list (click me)</summary>
```text
src/rapids_dependency_file_generator/_config.py:171: error: Argument 1 to "_parse_outputs" has incompatible type "object"; expected "Union[str, list[str]]"  [arg-type]
src/rapids_dependency_file_generator/_config.py:173: error: No overload variant of "list" matches argument type "object"  [call-overload]
src/rapids_dependency_file_generator/_config.py:173: note: Possible overload variants:
src/rapids_dependency_file_generator/_config.py:173: note:     def [_T] list(self) -> list[_T]
src/rapids_dependency_file_generator/_config.py:173: note:     def [_T] list(self, Iterable[_T], /) -> list[_T] …
```
=> chore(refactor): prefer typing.Any to 'object' for type hints

src/rapids_dependency_file_generator/_config.py, src/rapids_dependency_file_generator/_rapids_dependency_file_generator.py, tests/examples/pyproject-no-extras/dependencies.yaml, tests/test_examples.py, tests/test_rapids_dependency_file_generator.py
Contributes to #87.
`mypy` caught some code that's treating `File.extras` as if it's unconditionally not `None`, when it actually can be `None`.
```text
_rapids_dependency_file_generator.py:426: error: Argument "extras" to "make_dependency_file" has incompatible type "FileExtras | None"; expected "FileExtras"  [arg-type]
```
This fixes that by correcting some types hints and explicitly raising an error if a `None` makes it to the part of `make_dependency_file()` where that `extras` field is nedeed.
Prior to this change, given a `dependencies.yaml` like this:
```yaml
files:
beep_boop:
output: pyproject
includes:
- run_deps
pyproject_dir: .
dependencies:
run_deps:
common:
- output_types: [pyproject]
packages:
- fsspec>=0.6.0
```
`rapids-dependency-file-generator` would raise an error like …
=> fix: raise informative error if 'extras' key is missing for pyproject files

README.md, tests/test_cli.py
Contributes to https://github.com/rapidsai/build-planning/issues/31.
Over in https://github.com/rapidsai/devcontainers/pull/365, I'm proposing a change that depends on how `rapids-dependency-file-generator` handles duplicates in `--matrix` selectors.
See https://github.com/rapidsai/devcontainers/pull/365#discussion_r1687121294.
This proposes adding tests covering that behavior, to reduce the risk of accidentally removing that support in future refactorings.
=> test: add tests on handling of duplicate matrix selectors

recipe/meta.yaml
I saw conda builds in CI on #106 failing like this:
```text
Traceback (most recent call last):
File "/opt/conda/bin/conda-mambabuild", line 10, in <module>
- python >=3.9
- build
with channels:
The reported errors are:
- Encountered problems while solving:
-   - nothing provides requested build
```
Looks to me like this is due to the following set of circumstances:
* the conda package here has a dependency on `build`
* conda-forge stopped publishing it 2 years ago: https://github.com/conda-forge/build-feedstock
This fixes that by switching the dependency in the recipe from `build` to `python-build`.
I'm really not sure why this is just breaking now... the latest release of `build` at https://anaconda.org/conda-forge/build/files is a noarch package without any constraints that appear to …
=> chore(deps): require python-build in conda recipe

ci/publish/conda.sh
Part of issue: https://github.com/rapidsai/build-planning/issues/98
Uses [`find`]( https://www.man7.org/linux/man-pages/man1/find.1p.html )'s `-o` option to search for `.conda` or `.tar.bz2` files to upload
Once collected the `anaconda upload` command later should take care of the rest
=> chore(refactor): Search for `.conda` packages to upload too

.pre-commit-config.yaml
This project supports `python>=3.9`
https://github.com/rapidsai/dependency-file-generator/blob/4e32ded33b3df70e88cff06bac59488fca74ae7f/pyproject.toml#L21
But is telling `pyupgrade` it supports `python>=3.8`.
https://github.com/rapidsai/dependency-file-generator/blob/4e32ded33b3df70e88cff06bac59488fca74ae7f/.pre-commit-config.yaml#L22-L25
This fixes that, and updates all the other hook versions (`pre-commit autoupdate`) since it's been a while.
I don't think so. That's being done across RAPIDS libraries in https://github.com/rapidsai/build-planning/issues/88 right now, but `rapids-dependency-file-generator` is used in many places outside of RAPIDS (see everything linked to https://github.com/rapidsai/dependency-file-generator/issues/89, for example).
For tools like this, I think we should …
=> chore(refactor): update pre-commit hook verions, pyupgrade target Python version

recipe/meta.yaml, renovate.json
The `renovate` bot just opened #112, trying to upgrade the CI image used in this repo for wheel builds / tests from `python:3.9` to `python:3.13`.
We don't want those types of updates... it's an intentional choice that `rapids-dependency-file-generator` wheels are built and tested on the oldest Python version this tool supports.
This PR attempts to tell `renovate` not to make such recommendations in the future. I saw "attempts" because I have no idea how to test this.
references suggesting this `ignoreDeps` field is the right way to do this:
* https://docs.renovatebot.com/configuration-options/#ignoredeps
* https://github.com/rapidsai/docker/pull/643#issuecomment-2168645396
=> fix: add host dependency on 'setuptools', ignore renovate Python updates

CONTRIBUTING.md, README.md
* Move the section regarding the test examples to `CONTRIBUTING.md`, this information is developer specific and resulted in broken links on pypi.org
* Remove the table of contents, as the anchor tags were similarly broken on pypi.org
* Misc spelling error fix.
Closes #121
=> fix(docs): Move developer specific docs from `README.md` to `CONTRIBUTING.md`

tests/examples/overlapping-deps/dependencies.yaml, tests/test_rapids_dependency_file_generator.py
When installing Matplotlib with Conda, use `matplotlib-base`. This is more lightweight as it doesn't pull in a bunch of GUI bits that we don't use.
ref: https://conda-forge.org/docs/maintainer/knowledge_base/#matplotlib
=> chore(ci): use 'matplotlib-base' instead of 'matplotlib' in conda examples

ci/publish/conda.sh
Contributes to #143 
There, I noticed that when `anaconda upload` was complaining about a file not existing, it was breaking the log message onto 2 lines like this:
```text
Error:  File "/tmp/conda_output/noarch/rapids-dependency-file-generator-1.19.0-py_0.conda
" does not exist
```
That made me think "maybe an extra newline is getting in there".
I'm confident now that that's exactly what's happening. I think the changes in #139 switching from `find` to `readarray` introduced a trailing newline into the list of packages fed to `anaconda upload`, similar to what's described here: https://unix.stackexchange.com/questions/519914/how-to-remove-new-line-added-by-readarray-when-using-a-delimiter
We didn't catch that because merging that PR didn't trigger a release.
This PR:
* reverts to the …
=> fix(ci): revert method of finding conda packages to upload

.pre-commit-hooks.yaml, src/rapids_dependency_file_generator/__init__.py, src/rapids_dependency_file_generator/_cli.py, src/rapids_dependency_file_generator/_rapids_dependency_file_validator.py, src/rapids_dependency_file_generator/_warnings.py, tests/test_cli.py, tests/test_rapids_dependency_file_validator.py
Resolves https://github.com/rapidsai/dependency-file-generator/issues/162
=> feat: Warn when a dependency set is unused
